export const ACTION = {
  SET_WINDOW: "SET_WINDOW",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_VENDORS: "SET_VENDORS",
  SET_STOCKS: "SET_STOCKS",
  SET_EXPIRED_STOCKS: "SET_EXPIRED_STOCKS",
  SET_NEAR_EXPIRY_STOCKS: "SET_NEAR_EXPIRY_STOCKS",
  SET_SETTLEMENTS: "SET_CURRENT_SETTLEMENTS",
  SET_CURRENT_SETTLEMENT: "SET_CURRENT_SETTLEMENT",
  SET_TRADE_ANALYSIS: "SET_TRADE_ANALYSIS",
  SET_COMPANIES: "SET_COMPANIES"
}