export const ACTION = {
  SET_WINDOW: "SET_WINDOW",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_VENDORS: "SET_VENDORS",
  SET_STOCKS:"SET_STOCKS",
  SET_EXPIRED_STOCKS:"SET_EXPIRED_STOCKS",
  SET_NEAR_EXPIRY_STOCKS:"SET_NEAR_EXPIRY_STOCKS",

}